include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    prefer_const_constructors: true
    sort_constructors_first: true
  plugins:
    - custom_lint
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
