// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP27cx0yT0VqQlEoxop1DKvdx0yeIMUxI',
    appId: '1:840311286574:android:182f4e48962ce19e2468bf',
    messagingSenderId: '840311286574',
    projectId: 'fb-auth-riverpod-65472',
    storageBucket: 'fb-auth-riverpod-65472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuVIcKC7RKtO2M7xXScqlp_Yi5mMlFoSo',
    appId: '1:840311286574:ios:1c97c822de91e5d32468bf',
    messagingSenderId: '840311286574',
    projectId: 'fb-auth-riverpod-65472',
    storageBucket: 'fb-auth-riverpod-65472.firebasestorage.app',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIupAkCnEpFap1BBnk5XNt8Zvqq_jte4',
    appId: '1:840311286574:web:78244cb10e9952e52468bf',
    messagingSenderId: '840311286574',
    projectId: 'fb-auth-riverpod-65472',
    authDomain: 'fb-auth-riverpod-65472.firebaseapp.com',
    storageBucket: 'fb-auth-riverpod-65472.firebasestorage.app',
  );

}