name: infinite_scroll
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.7.2 
  flutter_lints: ^5.0.0 
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
